name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test server
      run: |
        npm run install --prefix server
        npm run build --prefix server
        npm run test --prefix server

    - name: Build and test webapp
      run: |
        npm run install --prefix webapp
        npm run build --prefix webapp
        npm run test --prefix webapp

    - name: Build plugin
      run: |
        npm run install --prefix plugin
        npm run build --prefix plugin

    - name: Run integration tests
      run: |
        npm run install --prefix test
        npm run test --prefix test
